import Head from "next/head";
import Image from "next/image";
import {
  Container,
  Heading,
  Link,
  Flex,
  Box,
  VStack,
  Button,
  SimpleGrid,
  useColorMode,
} from "@chakra-ui/react";
import Navigation from "../components/Navigation";
import RecipeCard from "../components/RecipeCard";
import styles from "../styles/Home.module.css";

const foods = [
  {
    imageUrl:
      "https://www.liveeatlearn.com/wp-content/uploads/2019/03/how-to-make-banana-nice-cream-photo-14.jpg",
    imageAlt: "Banana Nice Cream",
    title: "Banana Nice Cream",
    time: "6 hours",
    rating: 4,
  },
  {
    imageUrl:
      "https://cdn.loveandlemons.com/wp-content/uploads/2014/04/IMG_00201.jpg",
    imageAlt: "Carrot Cake",
    title: "Vegan Carrot Cake",
    time: "6 hours",
    rating: 3,
  },
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Grace & Samuel Cookbook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Container>
        <Box>
          <Heading as="h1" size="2xl" mb="10" color="brand.800">
            Welcome to Our Cookbook
          </Heading>
        </Box>
        <Heading as="h2" size="xl" mb="4">
          Recipe of Grace and Samuel
        </Heading>
        <SimpleGrid gap="4">
          {foods.map((p, key) => (
            <RecipeCard key={key} data={p} />
          ))}
        </SimpleGrid>
        {/*     
        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>

          <p className={styles.description}>
            Get started by editing{" "}
            <code className={styles.code}>pages/index.js</code>
          </p>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/master/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main> */}
      </Container>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
